### ISSUE TITLE
Newly added IWAD files can appear as a local file

### ISSUE THREAD

**Issue by guynamederick** [nstlaurent/DoomLauncher#169]
If adding a new IWAD file for the first time, while it is treated as an IWAD and appears in the IWad tab, the IWAD file can appear as a local file during the runtime it was added. Closing Doom Launcher and opening it up again will have the IWAD file not appear as a local file anymore. Attempting to readd the IWAD file during future runtime uses will not have it appear in the Local tab.

**Comment by nstlaurent** [comment]
Fixed with:
https://github.com/nstlaurent/DoomLauncher/pull/171
