### ISSUE TITLE
Can't scroll in "Add Files"

### ISSUE THREAD

**Issue by ak1dd** [nstlaurent/DoomLauncher#181]
Longtime user of DoomLauncher.   Love it.

With 3.10 I have noticed that most time when I choose a wad, hit play and then "Add Files", the resulting window will not scroll using keyboard or mouse.  If I use the scroll wheel on my mouse a section of about the bottom 2/3rds of the listbox will scroll but it is all garbled.   See attached screenshot.  I am unable to select any additional files that require me to scroll.

This never happened with any previous version.  I don't think it is a video driver issue as the listbox won't scroll and I've never seen this behavior in any other application.

I'm sure this isn't the case for everyone as it means you can't play any wads in which you have to scroll when adding.  Let me know if there is something I can do/provide to help understand what is going on.

![Annotation 2020-08-02 140518](https://user-images.githubusercontent.com/38289720/89123723-6e2a4380-d4c9-11ea-8b23-779c10debe2f.png)

**Comment by nstlaurent** [comment]
That is quite strange. I am unable to replicate it. Can you attach your DoomLauncher.sqlite file? Maybe there is a setting that is contributing.

**Comment by ak1dd** [comment]
Sure.   I'm certain it can't affect many people.   I do keep upgrading and have for over 2 years.   I really don't want to do a clean reinstall... :)
[DoomLauncher.zip](https://github.com/nstlaurent/DoomLauncher/files/5014505/DoomLauncher.zip)

**Comment by nstlaurent** [comment]
Unfortunately, I haven't been able to replicate the problem. If you are using the tile views, can you navigate to Settings -> View and change the View Type to Grid and let me know if the grids have the same problem in the main window?

**Comment by ak1dd** [comment]
I only use Tile views.   Just verified and toggled it on/off after restarting.

Just to make sure I'm clear, the problem doesn't happen when you are navigating wads/files via the tabs.   It only happens when I select a wad, double click it, then choose "Additional Files/Load Order" use the first icon on the left (New?).   The select File dialog appears.  If I try to scroll it, and I have several hundred wads, the display corruption happens in that listbox.

**Comment by ak1dd** [comment]
I have figured this out.   I'm not sure I'd call this a DL bug but rather a qt bug if I am correct.

I have a hiDPI screen.  qt controls are so tiny you can almost not even see them.   I "Fixed" this by using the Windows HiDPI settings for DoomLauncher.exe under Properties to "Override high DPI scaling behavior  Scale Performed by:"  And I was using "System (Enhanced)".    This does make the qt controls normal size but does cause the scrolling issue I am mentioning".    

I do notice that the qt controls in Inkscape and Gimp have both been updated and play nicer with HiDPI screens now - albeit not perfect.

I won't close this and leave it to your judgement as whether or not it is a bug to be addressed.  As more hidpi screen come along it will probably be more pervasive.

A workaround is to use the setting "System" instead of "System (Enhanced)".   Text/Icons/etc are blurry in DL but it all works as expected.

**Comment by nstlaurent** [comment]
Thank you for putting in the effort to figure out the problem. This one has been bugging me for quite some time. I will play around with it and see what I can do.

**Comment by nstlaurent** [comment]
I was able to replicate this changing my DPI scale to 150% and changing the compatibility option. I'm not entirely sure what this option is doing but it's not allow the control to redraw properly which is why it is all cut off. I was able to fix it by forcing redraw on scroll. 

On Windows 10 changing DPI scale options everything looks very smooth. If I change the compatibility options then everything looks more blurry for me. Not sure why you need to set this option.

Anyway, this build should fix the issue:

[DoomLauncher_3.0.1.0.zip](https://github.com/nstlaurent/DoomLauncher/files/5136925/DoomLauncher_3.0.1.0.zip)
