### ISSUE TITLE
Unable to find statistics in the save file error

### ISSUE THREAD

**Issue by pizzapim** [nstlaurent/DoomLauncher#195]
After saving and exiting a PWAD I got the following error in a popup:
```
Unable to find statistics in the save file C:\Users\user\Documents\doom\gzdoom-4-4-2-Windows-64bit\Save\save7.zds.
```

The PWAD was Plutonia 2 and IWAD Plutonia. I played this WAD before without this problem also on GZDoom through the Doom Launcher. The statistics do seem to be up-to-date.

If you can point me in the right direction I would be happy to look into this problem myself. Thanks for the awesome program!

**Comment by nstlaurent** [comment]
Hi,

I just tested with GZDoom 4.4.2 using Plutonia 2 and had no problems. Could you attach the save file so I can take a look? Thanks!

**Comment by pizzapim** [comment]
Here is the save file:

[save7.zip](https://github.com/nstlaurent/DoomLauncher/files/5261147/save7.zip)

I loaded the save file again just now and don't see any problems. Saving (to another slot) also doesn't produce an error.

**Comment by nstlaurent** [comment]
I think this is similar to the other problem with GZDoom stats someone else has reported. It is very random. This build should resolve it either way:

https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/35419254/artifacts

**Comment by pizzapim** [comment]
Thanks for the quick fix! I will close the issue as I can't reproduce it anyways.
