### ISSUE TITLE
Feature Request: -config and -savedir support (and maybe templates)

### ISSUE THREAD

**Issue by Tony556** [nstlaurent/DoomLauncher#20]
I use Doom Launcher to have a lot of different copies of the same engine in order to keep my config files separate (as they can interfere easily). If it was possible to, in the source ports settings, have a folder of many .ini's that could be chosen from when launching something. For example: 

![cconfig](https://user-images.githubusercontent.com/4276171/44949799-ce03a580-aded-11e8-863c-5e4de1ed9e8a.png)

And maybe something similar with save directories? :)

Edit: Sorry, forgot to mention templates. It could be something that will automagically select the previously-defined engine, config, savedir, and maybe additional pwads. Similar to ZDE's quick profiles.

**Comment by robbinsrush** [comment]
The config might fit better in the Source Port options itself, actually. So you could have multiple versions of the same Source Port added with a different config every time

**Comment by Archov** [comment]
If I find time I might actually take a crack at this in the near future. I've got some other enhancements I think I can bring to the table on top of what he's asking here, but templates and ini handling are both my biggest asks as well.

**Comment by ak1dd** [comment]
the save game feature would be useful for everyone...  my save lists across mods is endless and confusing.

**Comment by hobomaster22** [comment]
> 
> 
> If I find time I might actually take a crack at this in the near future. I've got some other enhancements I think I can bring to the table on top of what he's asking here, but templates and ini handling are both my biggest asks as well.
> 
> (Side note, I'll probably Fix [Issue 49](https://github.com/hobomaster22/DoomLauncher/issues/49) as part of my implementation.

If you do work on this I would like these issues to be on separate merge requests. I'm wrapping up some of the bugs and plan on merging development into master soon and releasing. Then I will probably work on [Issue 49](https://github.com/hobomaster22/DoomLauncher/issues/49).

Also, I'm genuinely curious as to why you have different ini files for zdoom?

**Comment by Tony556** [comment]
@hobomaster22 

My main reason for having separate .ini files is both complex and simple:

Mod config conflicts and bloat.

Even Project Brutality and Brutal Doom have conflicting keybinds. Plus, if I stop using a mod, I don't want its config flags to stick around and possibly cause issues with new sessions.

Also, certain mods will need certain options changed (like the HUD scale) that will look wrong when that mod is not being used.

**Comment by nstlaurent** [comment]
@Tony556 I am going to close this as the profile support meets the requirements here. You can add another profile with different pwads and specify config and savedir in the extra params field.

You can check out the latest development build.
