### ISSUE TITLE
Ability to mark WADs as completed and hide from view

### ISSUE THREAD

**Issue by robrich82** [nstlaurent/DoomLauncher#205]
I currently use a tag to mark WADs I've finished playing, I'd quite like to be able to hide any WADs with the tag from view (optionally) so I can easily see what I haven't played yet.

**Comment by nstlaurent** [comment]
Added option to tags called "Exclude from other tabs". This way you can make a Completed tag and set it to exclude and it will no longer show.

https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/35805939/artifacts
