### ISSUE TITLE
Unhandled exceptions from certain searches on Id Games tab.

### ISSUE THREAD

**Issue by DrR0Ck** [nstlaurent/DoomLauncher#208]
[DoomLauncher exception.txt](https://github.com/nstlaurent/DoomLauncher/files/5411518/DoomLauncher.exception.txt)
When running certain searches on the Id Games tab, I am getting unhandled exceptions. Some searches work without issue, but searches for "vader" and "cheesewheel" consistently throw exceptions.  Exception text content is attached.  Please let me know if more information is required or the issue is due to something on my end.

**Comment by nstlaurent** [comment]
Thanks! Strange that was unable to reproduce the problem, but from the exception I can see how it can happen. Let me know if this build resolves the issue.

https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/35863773/artifacts

**Comment by DrR0Ck** [comment]
Wow - incredibly fast fix.  I can confirm I am able to run those searches now.  If I run into anything else that causes an issue, I'll let you know.  Thanks!
