### ISSUE TITLE
Add source port statdump support for Woof

### ISSUE THREAD

**Issue by wrkq** [nstlaurent/DoomLauncher#223]
Hi!

I didn't see RonnieColeman posting about this in your Doomworld thread so here's the thing. :)
Sorry for not submitting a trivial pull request but Git is way too weird for me to handle it successfully.

Fabian has made Woof support -statdump compatible with Chocolate and Crispy.
So I believe you can just create a thin Chocolate-derived class exactly like CrispyDoomSourcePort.cs.

Ref: https://github.com/fabiangreffrath/woof/commit/6039293acaaf09a0cabe8573faac5fbc5d60075f
and https://www.doomworld.com/forum/topic/112333-this-is-woof-300-nov-30-2020-updated-winmbf/?do=findComment&comment=2227135

Thanks!

**Comment by nstlaurent** [comment]
Thanks for letting me know. This is done for the next version. You can download it here if you like:

https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/36856919/artifacts

The update should be officially pushed out this weekend.

**Comment by wrkq** [comment]
Happy to confirm it seems to work fine.
The "enable statistics" checkbox is active, the port is started with -statdump parameter, and the stats.txt file is properly parsed back into DoomLauncher.
Thank you very much!

**Comment by fabiangreffrath** [comment]
Thanks a lot to both of you!
