### ISSUE TITLE
[BUG]Blank window on add files , play menu on 3.2.0 version. thank y

### ISSUE THREAD

**Issue by Caiuzx** [nstlaurent/DoomLauncher#227]
there is on my doomlauncher 3 a bug for select file(add files- play menu ) as my screenshot . On version 3.2.0

thanks for your app.

ps : excuse for my english , I hope you understand :D

PS : original my topic.
https://www.doomworld.com/forum/topic/69346-doom-launcher-doom-frontend-database-v320-122020/?page=10&tab=comments#comment-2233864

sorry for crossposting, but i believe is a major bug 💯

**Comment by nstlaurent** [comment]
Hi,

Taking a look. Thanks for pointing it out.

**Comment by nstlaurent** [comment]
Fixed. Pushed in 3.2.1 release.
