### ISSUE TITLE
"Load Latest Save" not working in GZDoom

### ISSUE THREAD

**Issue by andrikpowell** [nstlaurent/DoomLauncher#235]
If I select the "Load Latest Save" option in the latest DoomLauncher Release, I get an error message saying 

> Could not read savegame 'C:/Program.zds'

You can also see in a screenshot here:
![GZDoom savegame error](https://user-images.githubusercontent.com/61759217/113224494-31c60780-9251-11eb-9425-1becbc88cea3.jpg)

In the "Preview Launch Parameters" it looks like this:
![launch-parameters](https://user-images.githubusercontent.com/61759217/113224544-4f936c80-9251-11eb-8368-c01fc125a680.jpg)

I actually just realized that to fix this issue, quotes need to be added around the added '-loadgame' parameter.
I think the error is caused by the space in "Program Files" the loadgame path (that's why it stops at "C:\Program.zds"):

>  -loadgame C:\Program Files\DOOM\Source Ports\GZDoom\Saved Games\save89.zds
needs to be:
>  -loadgame "C:\Program Files\DOOM\Source Ports\GZDoom\Saved Games\save89.zds"

**Comment by nstlaurent** [comment]
Will have this resolved soon, thanks!

**Comment by nstlaurent** [comment]
Fixed and merged to development.
