### ISSUE TITLE
Saves restoring themselves after being deleted in GZDoom

### ISSUE THREAD

**Issue by andrikpowell** [nstlaurent/DoomLauncher#236]
So this is kind of complicated issue I've run across, so I'll use the two wads "Unholy Realms" and "Alien Vendetta" in this example.

So first off I'll say that I was super excited when the "Alt Savegame Path" option was added to Source Ports since I like my GZDoom parent folder to be decluttered using a "Saved Games" folder.

I have however run into a weird issue with how DoomLauncher manages saved games.

Example:
> Say I play "Alien Vendetta" and I created a save called "Alien"... Say I play to map25 or something and then I start save scumming a couple more saves named "a", "aa", and "aaa". If I quit GZDoom, those saves will show up in the saved games panel under "Alien Vendetta" in DoomLauncher (as intended).

> Now say I run "Unholy Realms" and I decide that I no longer need the save games "a", "aa" and "aaa" from "Alien Vendetta". And so I delete them in GZDoom. If I quit "Unholy Realms" and relaunch "Unholy Realms", those save games will be gone as intended.

> However if I decide to launch "Alien Vendetta" after I deleted those saves, the save games "a", "aa" and "aaa" will undelete themselves and show up in my saved games in GZDoom.

I assume this is caused by DoomLauncher not noticing when save games are deleted while playing a mod that those save games are not managed by.

This is an issue for me because the save game management in DoomLauncher is lacking (no screenshot, map information, etc), and I'd prefer to manage my save games in GZDoom.

This also causes an issue with how GZDoom's autosaves work, since by default GZDoom creates/overwrites autosaves at the beginning of a map. Autosaves will be constantly be changing which mod they correspond to.

A potential solution to this issue, would be for DoomLauncher to refresh it's save games database after/before launching a mod, and then it would keep it up to date. (Obviously I don't really know how it's being done currently and/or if this is possible or not).

**Comment by nstlaurent** [comment]
Done and merged to development.
