### ISSUE TITLE
Alias or explicit support for dsda-doom (PrBoom+ fork)

### ISSUE THREAD

**Issue by ZeroKnight** [nstlaurent/DoomLauncher#237]
There's been a recent fork of PrBoom+ that mostly adds features related to demo playback and speedrunning; all in all not too heavily modified. Would it be possible to add support or in some way alias it to PrBoom+ as far as DoomLauncher feature detection goes? More precisely, enabling the "**Save Statistics**" and "**Load Last Save**" features for dsda-doom.

Relevant links:
- https://www.doomworld.com/forum/topic/118074-dsda-doom-source-port-v0180/
  - [Latest Windows Build](https://www.doomworld.com/applications/core/interface/file/attachment.php?id=118770)
- https://github.com/kraflab/dsda-doom

**Comment by nstlaurent** [comment]
Done, and merged to development. Thanks for letting me know.
