### ISSUE TITLE
Support for EE's pke format files?

### ISSUE THREAD

**Issue by MattFright** [nstlaurent/DoomLauncher#240]
The launcher seems to be able to _add_ pke files normally, but it doesn't seem to be able to actually read the file, as it doesn't list amount of maps and upon opening the game, it's like the file wasn't even loaded (probably really wasn't). 

Could we get support for pke format files anytime soon?

**Comment by nstlaurent** [comment]
Shouldn't be a problem assuming it's a zip file like pk3s etc. Can you link an example so I can make sure it works correctly?

**Comment by MattFright** [comment]
Hey, sorry for the late reply. You can test it with Skillsaw's Heartland here for example: https://www.doomworld.com/forum/topic/120175-heartland-final-version-available-on-idgames

**Comment by nstlaurent** [comment]
Someone on doomworld commented and I figured out that heartland was was bringing up the pke format. The pke extension will automatically be added in the update I pushed out this morning.
