### ISSUE TITLE
Title Pic

### ISSUE THREAD

**Issue by shaunt55** [nstlaurent/DoomLauncher#242]
Hi
The title pic on the right bar is always the same. Is there a way to make them individual as in doom, Doom 2 etc.

**Comment by nstlaurent** [comment]
Load the IWAD with GZDoom in Doom Launcher. Hit the print screen button to take a screenshot and exit. Doom Launcher will automatically pull screenshots. You can alternatively click the 'Add File' button right above the Screenshots tab if you have an image on your computer you wanted to add manually.

**Comment by shaunt55** [comment]
ThanksSent from my Huawei phone-------- Original message --------From: Nick ***@***.***>Date: Thu, 6 May 2021, 14:59To: nstlaurent/DoomLauncher ***@***.***>Cc: shaunt55 ***@***.***>, Author ***@***.***>Subject: Re: [nstlaurent/DoomLauncher] Title Pic (#242)
Load the IWAD with GZDoom in Doom Launcher. Hit the print screen button to take a screenshot and exit. Doom Launcher will automatically pull screenshots. You can alternatively click the 'Add File' button right above the Screenshots tab if you have an image on your computer you wanted to add manually.
