### ISSUE TITLE
support for adding mods in directory/folder form

### ISSUE THREAD

**Issue by UndeadRyker** [nstlaurent/DoomLauncher#250]
AFAIK this would really only benefit ZDoom source ports, but would still be extremely useful for load orders and whatnot in multiplayer. ZDoom can load mods in an unpackaged form using a folder as long as that folder is structured properly in a .zip or .pk3 format.
![example](https://user-images.githubusercontent.com/26333062/154800795-493e4b54-0731-430f-aa54-2e02684c1cea.png)
For example, I can load the folder, "arcanum", as if it was a .pk3 in GZDoom. This is because the innards of the folder is structured like a .pk3 file that the source port can read.

There are benefits to why people would do this. One, for easier mod development. Two, for being able to easily pull updates for mods from Git. ZDL (or at least, [the updated version](https://github.com/lcferrum/qzdl)) does this by adding a separate button to allow directories to be loaded as mods. This is also why I find "Create .ZIP from directory" to be an unattractive option for convenience purposes just for this use case scenario.

Due to the nature of why people would do this, I'd be fine if Doom Launcher doesn't even offer the option to attempt to manage them. It would go against the point of why it's such a useful feature to have. I have file management set to off anyway, myself.

Thanks a lot for Doom Launcher btw!

**Comment by UndeadRyker** [comment]
This is somewhat related to #95 now that I rechecked all the other issues.

**Comment by nstlaurent** [comment]
This feature looks good. It would definitely work like adding an unmanaged file and would have to be forced that way. I didn't know GZDoom supported this. Does it work just by passing the folder path with -file?

**Comment by UndeadRyker** [comment]
> Does it work just by passing the folder path with -file?

Yes! Sorry for forgetting to mention that. Glad to hear you like the suggestion. To load the mod in pic-related for example, it would be `-file F:\Repositories\Accensus\arcanum`.

**Comment by nstlaurent** [comment]
Here is a test build supporting directories if you would like to try it out:
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/42680090/artifacts

**Comment by UndeadRyker** [comment]
Sweet, this is extremely useful and it's working. Thanks! My only suggestion to make this perfect would be to use the traditional file explorer menu like so (from ZDL): 
![image](https://user-images.githubusercontent.com/26333062/155358539-c116d36e-7f56-405c-99de-562c122fa8bb.png)
I've found that the current "tree" view makes it inconvenient for quickly loading multiple directories that are inside another directory that isn't on your desktop on your main drive. For me, when using the tree view, I have to navigate to my repositories folder on my external drive, from my Desktop on my main drive every time I add one. It's quite a timesink if you have a lot of directories waiting to be added.

When using this fire explorer view instead, it saves the parent location of where the last directory was accessed, so I'm easily able to go down the list. It would also make it more consistent with how Doom Launcher already handles files, as it automatically opens up the location of the last file I added.

Unfortunately, this way still doesn't allow for ctrl-clicking multiple folders at once in one go, so it would be sweet if there's some way to make this process more streamlined than I suggested. But in the meantime, this is great for now!

**Comment by nstlaurent** [comment]
Yeah, that dialog sucks. For some reason Microsoft hasn't exposed the nicer one to C# so I can't easily access it. Changing this would have to be it's own task. I figure most people are going to use the drag and drop feature anyway. This lets you find them however you want, and you are able to select multiple etc.
