### ISSUE TITLE
add current folder to the sortable columns?

### ISSUE THREAD

**Issue by rye-74** [nstlaurent/DoomLauncher#252]
Add current folder to the sortable columns?

This would be a great feature I would like to see added as all my mods are in folders with the proper names and in many cases the wads, zips or pk3s are hard to determine what it is by the filename alone. Unfortunately, mod authors don't always consistently name their files.

![Screenshot 2022-04-15 111312](https://user-images.githubusercontent.com/56748990/163588245-2150e8c9-b12a-4285-982b-1d5ea672b3b8.png)

**Comment by nstlaurent** [comment]
Hi,

Are these files unmanaged and you want to see the full path to the file? I can add a column to show the full path like:
C:\SomeFolder\brtualv21.pk3

**Comment by rye-74** [comment]
i dont think full path would be helpful (TMI) but current or last folder
would be ideal.

So
C:\SomeFolder\another folder\Brutal Doom\brtualv21.pk3
would just be *Brutal Doom *in the column.

**Comment by nstlaurent** [comment]
This has been completed and will be available in the next release. The current development build is below if you want it now. It will have all new features for the release including this one.
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/43509457/artifacts

**Comment by rye-74** [comment]
Awesome, thanks!
