### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by Dezaimasu** [nstlaurent/DoomLauncher#253]
I have a lot of tags with "Exclude from other tabs" option enabled. These files are also excluded from "Local" category, so if you want to find some file, you have to search in each tab one by one.

Maybe files shouldn't be excluded from Local category? When adding files from here
![image](https://user-images.githubusercontent.com/1636242/167521162-c5c194d2-cf51-438a-a126-30dbd45eb00b.png)
you have every single file included in Local tab
![image](https://user-images.githubusercontent.com/1636242/167521233-ae052acb-9237-407d-bbb1-f333f9c691f4.png)
even from "excluded" tags.

What I'm asking is some way to search across all files. 
Maybe "Local" tag should include all files so the behavior would be consistent in main window and in "select file" dialog.
Or maybe some "Global search" checkbox near the "Auto search" checkbox if you don't want to change how "Local" tag works.

**Comment by nstlaurent** [comment]
I'm thinking I might take the checkbox approach. It will hopefully be the most intuitive while keeping the existing functionality. It looks like the select file doesn't take excluded tags into account at all, which is probably OK.

**Comment by nstlaurent** [comment]
Added the checkbox. Will be available in the next release. The current development build is below if you want it now. It will have all new features for the release including this one.
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/43509457/artifacts
