### ISSUE TITLE
Add option to put custom screenshots if TITLEPIC is not found

### ISSUE THREAD

**Issue by OmegaZeroXIII** [nstlaurent/DoomLauncher#256]
Good morning, the truth is, without a doubt, the program is very cool, but organizing some things, for example, I put No Rest for the Living in my "Doom 2 Wads" list, but since the NERVE.WAD file does not have a TITLEPIC, the program places the images by default that brings but I would like there to be an option to put it yourself if the system does not find a TITLEPIC

**Comment by nstlaurent** [comment]
You can right now. The screenshots section at the bottom has a bunch of icons for options. One of them will be add file and you select any image you want. Once it's added you will have to leave the tab and come back or restart Doom Launcher to get the preview image in the tile to update.

**Comment by OmegaZeroXIII** [comment]
If I just realized hahaha I think I did not notice that I am missing to configure the screenshots folder in the launcher. Sorry for the inconvenience and thanks for such a great tool

**Comment by nstlaurent** [comment]
No problem, thanks!
