### ISSUE TITLE
Doom Launcher giving SQL logic error

### ISSUE THREAD

**Issue by Turbine2k5** [nstlaurent/DoomLauncher#259]
DL throwing SQL issue upon startup. Screenshot and Details of error provided.

![DL Issue](https://user-images.githubusercontent.com/55166453/183277228-d0aa95ec-7f3f-498d-83c0-546ee0d954f5.png)
[DL issue.txt](https://github.com/nstlaurent/DoomLauncher/files/9276248/DL.issue.txt)

**Comment by nstlaurent** [comment]
Download ReleaseBuild\DoomLauncher_3.6.0.0.zip from this build:
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/44396202

Overwrite DoomLauncher.exe from the zip and it should be good.

Do you know what version you were updating from? The section that broke was pushed for a version that is almost 2 years old.

**Comment by Turbine2k5** [comment]
I did download 3.6.0.0 via the update function from a past version of DL. I tried repairing it with the 3.6.0 release from the repo, but I still get this error.

**Comment by Turbine2k5** [comment]
Went ahead and copied all files from the zip. Now I'm receiving a new error:
![dl issue](https://user-images.githubusercontent.com/55166453/183286552-28ab91d2-3407-4fd6-883f-1495c92493cd.png)
[DL issue.txt](https://github.com/nstlaurent/DoomLauncher/files/9276601/DL.issue.txt)

**Comment by nstlaurent** [comment]
The issue may go away if you restart the app. Since the updated was interrupted it may still be an issue. If it is manually go to the folder and make sure these files are deleted:
SQLite.Interop.dll, SQLite.Interop.dll.bak, 7z.dll

**Comment by Turbine2k5** [comment]
Deleted those files in both the main directory, as well as the x64 and x86 directories. Now I get this:

System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at DoomLauncher.MainForm.InitFileCheck(String initFile, String file, Boolean directory)
   at DoomLauncher.MainForm.VerifyDatabase()

**Comment by nstlaurent** [comment]
Check if there is a file named DoomLauncher_.sqlite and delete it. Not sure why it wouldn't have access to clear this out this file. Also check for a folder named GameFiles_ with an underscore as well. Hopefully that should be it.

**Comment by Turbine2k5** [comment]
Deleted DoomLauncher_.sqlite and there was no folder called GameFiles_. Now I get an error box that says "Initialization failure. Could not find DoomLauncher database.

**Comment by nstlaurent** [comment]
There should be a folder named Backup. Copy the latest file and put it in the main DoomLauncher directory and rename it to DoomLauncher.sqlite

**Comment by Turbine2k5** [comment]
I do not have a folder called Backup.

**Comment by nstlaurent** [comment]
Forgot you ran the installer. It would be in this folder path:
C:\Users\your_username\AppData\Roaming\DoomLauncher

It's the same procedure, just copy and rename in that directory instead.

**Comment by Turbine2k5** [comment]
![DL Issue](https://user-images.githubusercontent.com/55166453/184092369-8769a8de-3b52-4fe8-8aac-74b07de14057.png)
[DL issue.txt](https://github.com/nstlaurent/DoomLauncher/files/9307207/DL.issue.txt)

**Comment by nstlaurent** [comment]
Running the latest installer should clear this up.
https://github.com/nstlaurent/DoomLauncher/releases/download/3.6.1/DoomLauncher_3.6.1.0_install.zip

**Comment by SirKnightTG** [comment]
I'm seeing the same issue as in the original post with the 3.6.1.0 installer.

**Comment by nstlaurent** [comment]
Make sure you have a GameFiles directory and DoomLauncher.sqlite file in this location:
C:\Users\your_username\AppData\Roaming\DoomLauncher

Delete these files/folders if they exist in the program files location:
C:\Program Files (x86)\Doom Launcher

GameFiles
DoomLauncher.sqlite
DoomLauncher_.sqlite

**Comment by Turbine2k5** [comment]
I still receive the Archived column error.

**Comment by nstlaurent** [comment]
I finally nailed down all the problems updating from this old version. Run the updated installer here and you should be all set.
https://github.com/nstlaurent/DoomLauncher/releases/download/3.6.2/DoomLauncher_3.6.2.0_install.zip

**Comment by Turbine2k5** [comment]
Program started and ran with no issues. Thank you for the help.
