### ISSUE TITLE
Running Doom Launcher through Steam via Dosbox

### ISSUE THREAD

**Issue by LPascholatti** [nstlaurent/DoomLauncher#267]
Hi there, I've used to run Doom Launcher by installing it on my Steam Folder and renaming the Doom Launcher application to `dosbox`, which made me able to execute it via Steam and load all my mods via there when running the Dos version. However, since the last update after doing that, it resulted on an exception error which crashed my the whole application. I'm also not able to copy and paste the code error here, since it crashes everything. 

![Doom Launcher Error](https://user-images.githubusercontent.com/53234431/214355282-58d66e6e-f882-4adb-9edb-48ee8f0245bf.png)

I've ended up having to delete the whole Doom Folder with all my logs from Doom Launcher after updating it. Since it was all on the same folder with the older install. It messed everything.

**Comment by nstlaurent** [comment]
How was it updated? It's missing files from the package.

Download the latest release zip file (not the installer):
https://github.com/nstlaurent/DoomLauncher/releases

Copy the contents of the zip file into your Doom Launcher folder to make sure it has all dlls.

**Comment by LPascholatti** [comment]
I ended up installing it 'the right way' and stopped doing that trick. Let's call it solved. Thanks!
