### ISSUE TITLE
Blank listings? 

### ISSUE THREAD

**Issue by ToeKnee02** [nstlaurent/DoomLauncher#270]
I’ve been using Doom Runner for awhile and it’s nice, but I would like to switch to something less… robust. I looked at a LOT of various launchers and the Doom Launcher appears to be exactly what I was looking for. And I LOVE the stat tracking feature, I wish more launchers utilized this. 

I’m having one problem with this though and i’m hoping you could help. I have a huge collection of various doom ports that require an emulator to run them (https://i.imgur.com/Nq713Z3.png). To get these to run properly with Doom Runner, I would just add the emulator as a source port and use  command line parameters to guide it to the rom. It worked perfectly and would just instantly launch into that version of doom.

With Doom Launcher however, it seems to require a file/iwad set to load and refuses to let you remove that file from the selection. This causes all the emulators to not properly load any of the games because it thinks it’s trying to load an iwad as well (which it has no idea what to do with). I even tried creating a “dummy” iwad that actually has nothing in it, and they still stop the emulators from working. 

Currently to get a “listing” added, you have either add a file, iwad, etc… So I was wondering if it could be made possible to add a “listing” without a file attached to it. Essentially just a blank listing so I can add my emulators, doom 3, etc… and it won’t be trying to load anything else with it, only loading what I have selected as the source port (emulator).

**Comment by nstlaurent** [comment]
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/46871947/artifacts

Added option for Extra Params Only
![image](https://user-images.githubusercontent.com/42744211/234067117-660c899a-fb03-40fe-b1b2-4c6587c661fe.png)

**Comment by ToeKnee02** [comment]
Thanks!! This is exactly what I was needing!
