### ISSUE TITLE
Profile Options Menu Hidden in Overflow Menu

### ISSUE THREAD

**Issue by SkyNinja** [nstlaurent/DoomLauncher#271]
Occurred on the build produced from the latest commit (b0b11054b47e4bf8a8344b6a4dcda50e50ed64c9).

![YgaujsLKmx](https://user-images.githubusercontent.com/4765557/235049038-f37ce8f8-1782-4fd6-85a7-650aafa8c02a.png)

This wasn't happening on the last version I was using, 2c73013585e2ce6e36ffde8bb44fbaccb07e1d84, as I made a few new profiles to test how the new launch option worked, and would've noticed at the time.

**Comment by nstlaurent** [comment]
Since I changed to a higher DPI Visual Studio changes the positions of all the elements when I change a form in the designer. This should hopefully put it back:
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/46911530/artifacts

**Comment by SkyNinja** [comment]
Sure enough the menu has returned home.
