### ISSUE TITLE
Can't fetch metadata from idgames for short filenames

### ISSUE THREAD

**Issue by Dezaimasu** [nstlaurent/DoomLauncher#275]
Two characters long to be precise.
Download them manually and add to DoomLauncher, and then click "Update metadata..."
Examples:
https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/tj
https://www.doomworld.com/idgames/levels/doom/megawads/et
![image](https://github.com/nstlaurent/DoomLauncher/assets/1636242/850ae54c-0fbe-4b36-8a53-732a5a0d26da)

**Comment by nstlaurent** [comment]
It's an issue with the idgames api. It will reject any request to search that is less than three characters.

**Comment by Dezaimasu** [comment]
Well that's sad, but not a big deal. Thanks for the info.

**Comment by Dezaimasu** [comment]
Hey, I found how to get around this limitation, it's really stupid. Just add `.zip` at the end.

- Gives an error:
https://www.doomworld.com/idgames/api/api.php?action=search&query=hg&type=filename&sort=date
- Query for the same filename, but successful:
https://www.doomworld.com/idgames/api/api.php?action=search&query=hg.zip&type=filename&sort=date

**Comment by nstlaurent** [comment]
That's cool. I will add it for the next release.

**Comment by nstlaurent** [comment]
Completed in 3.7.2
