### ISSUE TITLE
NET Framework error (SplitterDistance)

### ISSUE THREAD

**Issue by Contmotore** [nstlaurent/DoomLauncher#281]
I just updated DoomLauncher and got this error:

![image](https://github.com/nstlaurent/DoomLauncher/assets/86406901/f04df86c-cf95-478a-ab6e-4c741cb39373)
```
Unhandled exception has occured in your application. If you click Contintue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Value of '-2147483648' is not valid for 'SplitterDistance'. 'SplitterDistance' must be greater than 0.
Paramater name: SplitterDistance
```
When I continue I only see my tabs with empty columns, all wad files are gone.

**Comment by nstlaurent** [comment]
Let me know if this build fixes it. If not can you link me to your DoomLauncher.sqlite file?

https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/47668837

**Comment by Contmotore** [comment]
> Let me know if this build fixes it. If not can you link me to your DoomLauncher.sqlite file?
> 
> https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/47668837
Hi, sorry I'm not a programmer. How do I compile this? What programs do I need for this?

**Comment by nstlaurent** [comment]
It's already built in the artifacts tab. Usually to link to it directly so my bad.
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/47668837/artifacts

**Comment by Contmotore** [comment]
> 

Jup! This version works fine! Thnx!

**Comment by nstlaurent** [comment]
Just pushed the official release for this fix. Thank you very much for the help. 

https://github.com/nstlaurent/DoomLauncher/releases/tag/3.7.1
