### ISSUE TITLE
Microsoft .NET Framework errors

### ISSUE THREAD

**Issue by cosma-cpu** [nstlaurent/DoomLauncher#285]
Hello, I can't get this launcher to work on my computer, everytime I open it I got this message : 

Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à DoomLauncher.MainForm.SetupTabs()
   à DoomLauncher.MainForm.<Initialize>d__20.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à DoomLauncher.MainForm.<Init>d__161.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à DoomLauncher.Program.<Form_Load>d__1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9167.0 built by: NET481REL1LAST_B
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DoomLauncher
    Version de l'assembly : 3.7.0.0
    Version Win32 : 3.7.0.0
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/DoomLauncher.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.IO.Compression
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.IO.Compression.FileSystem
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
WadReader
    Version de l'assembly : 3.7.0.0
    Version Win32 : 3.7.0.0
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/WadReader.DLL
----------------------------------------
System.Memory
    Version de l'assembly : 4.0.1.1
    Version Win32 : 4.6.28619.01
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/System.Memory.DLL
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.SQLite
    Version de l'assembly : 1.0.115.5
    Version Win32 : 1.0.115.5
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
SevenZipSharp
    Version de l'assembly : 0.64.3890.29348
    Version Win32 : 0.64.3890.29348
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/SevenZipSharp.DLL
----------------------------------------
Octokit
    Version de l'assembly : 0.50.0.0
    Version Win32 : 0.50.0.0
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/Octokit.DLL
----------------------------------------
System.EnterpriseServices
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Version de l'assembly : 5.0.0.0
    Version Win32 : 5.0.20.51904
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
Microsoft.CSharp
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 4.8.9167.0 built by: NET481REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic.DynamicAssembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 4.8.9032.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
CheckBoxComboBox
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/User/Downloads/DoomLauncher_3.7.0.0/DoomLauncher/CheckBoxComboBox.DLL
----------------------------------------
Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

_____

And when I choose to quit when the prompt appear, I got this : 

System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à DoomLauncher.MainForm.BuildColumnConfig()
   à DoomLauncher.MainForm.HandleFormClosing()
   à System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   à System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   à System.Windows.Forms.Application.ExitInternal()
   à System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   à System.Windows.Forms.Control.WndProcException(Exception e)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   à System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   à System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   à System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   à DoomLauncher.Program.Main(String[] args)

**Comment by cosma-cpu** [comment]
Hello again, I found an older build, 3.2.0 and this one seems to work.

**Comment by nstlaurent** [comment]
Hi,

Is this from an update or the first time you are installing? Did you run the installer? What version of Windows are you using?

**Comment by cosma-cpu** [comment]
> Hi,
> 
> Is this from an update or the first time you are installing? Did you run the installer? What version of Windows are you using?

Hello, first time I'm using Doom Launcher. Windows 11 22H2 KB5028185 (22621.1992 build). No I didn't try the installer version, I will give a try.

**Comment by nstlaurent** [comment]
I figured out the problem. It came with a change in the configuration that had decimal values. The reason I couldn't catch it on my end is because in the US decimals are in the format 12.34 vs 12,34.  On start this would cause a crash on your computer, but works on mine because they are all set to US culture. Anyway, I just pushed 3.7.1 officially to fix this. Thanks for the help 👍 

https://github.com/nstlaurent/DoomLauncher/releases/tag/3.7.1
