### ISSUE TITLE
Map Limit per WAD/PK3

### ISSUE THREAD

**Issue by orbittwz** [nstlaurent/DoomLauncher#297]
Hey!
This is an amazing program, I like to be able to track and record everything for Doom Classic :)
As for some issues:
1. not a biggie but still, when you move from managed to un-managed configuration, and want to point the files to another location,
you can't and the only option is to remove the files and add again.
when you have saved progress or settings for said files, it's a shame to lose all this.
the only way to change it is to edit the sqllite db manually and point the record to the un-managed path of the file.
2. as the title says, I'm trying to add a megawad consists of almost 3000 maps, and the program stopped at 1091.
![image](https://github.com/nstlaurent/DoomLauncher/assets/45605734/8edbf71a-dbfd-44ae-a431-ff60ac23d950)
is there a map limit per file or I am not enabling some option??

please help me... thanks

**Comment by orbittwz** [comment]
OK update, it seems the program doesn't read hub files?
It was reading mapinfo file and skipped the mapinfo.hub2 and mapinfo.hub3 files...
So basically I have a problem?

**Comment by nstlaurent** [comment]
Yeah it looks like Doom Launcher isn't aware of reading mapinfo.* and will only read them if they are exactly mapinfo or zmapinfo.

I pushed a quick fix if you want to run the development build:
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/48828260/artifacts

**Comment by orbittwz** [comment]
Dude that's amazing!
Works...
![image](https://github.com/nstlaurent/DoomLauncher/assets/45605734/60028ac0-1ff5-459c-b7b7-7db5ba61f442)
Thanks so much 😃 🍆
