### ISSUE TITLE
GZDoom try to load up the latest save from wrong folder

### ISSUE THREAD

**Issue by jdznd** [nstlaurent/DoomLauncher#298]
I get this error message when I enable 'Load Latest Save' option and run GZDoom.

`Execution could not continue.

Cannot find savegame C:/Users/username/Saved Games/GZDoom/doom.id.doom2.commercial/C:/Users/username/Downloads/Doom/.exe/GZDoom/auto01.zds`

It should load save files from C:\Users\username\AppData\Roaming\DoomLauncher\GameFiles\SaveGames folder.

**Comment by nstlaurent** [comment]
Can you attach your DoomLauncher.sqlite file and the name of the file you are launching?

**Comment by jdznd** [comment]
[DoomLauncher.zip](https://github.com/nstlaurent/DoomLauncher/files/13802643/DoomLauncher.zip)

As for the name of the file, it doesn't matter. I happens to every wad I launch including doom2.wad without any additional wads or gameplay mods.

I tried again with new and clean launch environment. Put newly downloaded GZDoom and Doom Launcher (portable version) in C:\Doom folder, launch doom2.wad, beat MAP01 and create auto save, launch again with the setting checkboxed, and I get the same error message with slightly different path this time. 
"C:/Users/username/Saved Games/GZDoom/doom.id.doom2.commercial/C:/Doom/GZDoom/save00.zds"

**Comment by jdznd** [comment]
I tried GZDoom 4.8.0 and it's working. Maybe the issue is caused by the savegame storage change introduced with GZDoom 4.9.0.
https://zdoom.org/wiki/GZDoom_version_history

But shouldn't Doom Launcher just load save from the GameFile\SaveGames folder?

**Comment by nstlaurent** [comment]
GZDoom isn't checking if a full path is being passed and is preappending the path causing itself to break. You can check yourself by clicking Show Parameters and I get this for the DoomLauncher.sqlite file you sent.
 -loadgame "C:\Doom\GZDoom\auto01.zds"
 
I believe most set GZDoom to change the save_dir path somewhere else and then set that to the alt save directory Doom Launcher. I don't really use GZDoom so I had forgotten about this. There isn't an easy way to make this work out of the box without breaking versions before 4.9.

**Comment by jdznd** [comment]
It appears Doom Launcher trying to copy and load save files the way old versions of GZDoom used to behave.

GZDoom 4.9.0 and later versions store save files in user profile folder. So once I upgraded, the game shouldn't write save file in the main GZDoom folder anymore.

But I found that I have save files in GZDoom folder dates only few hours back. So I figured something is writing save game to the folder unnecessary. And it turns out Doom Launcher is doing that.

I deleted all the save files in the folder, ran GZDoom without Doom Launcher, and beat Doom 2 MAP01. No save file created in the folder. But once I ran using Doom Launcher, all the save files Doom Launcher manages for doom2.wad copied itself back to the folder.

**Comment by nstlaurent** [comment]
Yeah, it's an option that you can disable. Copy Save Files in the options.

**Comment by nstlaurent** [comment]
I've come up with a way that should work for everything. Passing the filename only without the path appears to work for all source ports and fixes GZDoom since it will append the appropriate nested path. I will push out a new release later today if I have time, you can run it yourself here:

https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/48859611/artifacts

**Comment by jdznd** [comment]
Thanks for the fix. It's working now.
