### ISSUE TITLE
Crash on source port launch from adding mod files twice

### ISSUE THREAD

**Issue by Sage009** [nstlaurent/DoomLauncher#301]
When I try launching a game with a mod like Walpurgis, the launcher tries to load the mod TWICE and causes the game to crash. This never happens when loading GzDoom directly with the same mod file.
![2024-05-15](https://github.com/nstlaurent/DoomLauncher/assets/32518671/e35a40d5-48e0-48c4-a721-6eccfe3bc4b0)

**Comment by nstlaurent** [comment]
What does Doom Launcher say when you click Show Parameters in the Launch window?

**Comment by Sage009** [comment]
I have Extra Parameters Only disabled, but this is what it says:
```
 -iwad "C:\Users\xxxxx\Downloads\GzDoom\HEXEN.WAD"
 -file "C:\Users\xxxxx\Downloads\GzDoom\+Walpurgis-JT-0.99.pk3"  

Supported Extensions: .wad,.deh,.bex,.pk3,.ipk3,.pk7,.pke

*** If files appear to be missing check the 'Select Individual Files' option and supported extensions options in the Source Port form of the selected source port.
```

**Comment by nstlaurent** [comment]
So here Doom Launcher is only telling to GZDoom to load it once which is correct.

It looks like GZDoom is adding it locally. Does that pk3 exist in your GZDoom directory?

**Comment by Sage009** [comment]
OHH now I get what the problem is. I assumed that since Doom Launcher has profiles when you click Play on a file, it would make a whole new config file when launching the game.
Yeah my GzDoom config has all my mods already in it separated per game. I'm only even giving Doom Launcher a shot because Zdoom Wars needs a different source port than GzDoom to play.
