### ISSUE TITLE
Fatal Error while starting some WADs with GZDoom

### ISSUE THREAD

**Issue by mikegonzalez2k** [nstlaurent/DoomLauncher#316]
[](url)I was trying to run the wad Box Doom, this happens on several other wads as well.  When starting using GZDoom I get an instant crash.  Note:  When I drop the wad directly into GZDoom it loads with no issues.
![image](https://github.com/user-attachments/assets/ab322cbe-b3f8-4311-b982-95e4dce71113)

I've attached a text file of the full error.  It seems to occur when loading the map info.
[DoomLauncher - BoxDoom.txt](https://github.com/user-attachments/files/17535465/DoomLauncher.-.BoxDoom.txt)

**Comment by nstlaurent** [comment]
If you click the show parameters link what does it show? Maybe there is an extra file being added.

**Comment by mikegonzalez2k** [comment]
Here are the launch parameters... it looks like it loads Doom.wad, then bd.wad

 -iwad "C:\Users\mikeg\AppData\Roaming\DoomLauncher\GameFiles\Temp\DOOM.WAD"
 -file "C:\Users\mikeg\AppData\Roaming\DoomLauncher\GameFiles\Temp\BD.wad"  

Supported Extensions: .wad,.deh,.bex,.pk3,.ipk3,.pk7,.pke

*** If files appear to be missing check the 'Select Individual Files' option and supported extensions options in the Source Port form of the selected source port.

**Comment by mikegonzalez2k** [comment]
I checked that wad and it's made specifically for Doom 1.  I should note my doom.wad is the Ultimate Doom wad, not the original.  Maybe that is the issue.

**Comment by mikegonzalez2k** [comment]
According to this forum there is an issue with UMapInfo when the map is formatted incorrectly depending on the level editor that was used to create it.  I guess I have to find a way to convert the map format so it's compatible.
https://www.doomworld.com/forum/topic/144923-issue-with-umapinfo/

**Comment by nstlaurent** [comment]
I just tested this myself with boxdoom.wad and it's an issue with GZDoom 4.13.1. I tested against GZDoom 14.11, Helion, and dsda-doom and loads fine.

**Comment by mikegonzalez2k** [comment]
I'll use that version, thanks.

**Comment by mikegonzalez2k** [comment]
Tested on GZDoom 4.11 and it works, closing ticket.
