### ISSUE TITLE
Automatically scan for TITLEPIC for preview

### ISSUE THREAD

**Issue by nstlaurent** [nstlaurent/DoomLauncher#86]
Pulling the TITLEPIC can be intensive so it should be done when the file is added. For existing files, an additional function will be needed to go through all the existing files in the library looking for the titlepic.

For ZDoom will need to check for MAPINFO/ZMAPINFO titlepage definition.

May want to add a checkbox in the options to enable/disable this option.

**Comment by Tony556** [comment]
Not too sure, but I think some WADs (like that new Doom Slayer Chronicles)
have animated backgrounds on their title screens, and as such I'm not sure
if they have proper titlepics. Could be totally wrong, though.

**Comment by hobomaster22** [comment]
There's probably going to be cases where I won't be able to pull anything. It will require some special checking for zdoom.
